

create table IF NOT EXISTS cursos (id_curso bigint generated by default as identity, nombre_curso varchar(300) not null, id_profesor bigint, primary key (id_curso));

create table IF NOT EXISTS cursos_estudiantes (id bigint generated by default as identity, id_curso bigint, id_estudiante bigint, primary key (id));

create table IF NOT EXISTS usuarios (id_usuario bigint generated by default as identity, clave varchar(255) not null, correo varchar(100) not null, nombre_usuario varchar(100) not null, rol varchar(255) not null, primary key (id_usuario));

alter table cursos add constraint fk_profesor foreign key (id_profesor) references usuarios;

alter table cursos_estudiantes add constraint fk_curso foreign key (id_curso) references cursos;

alter table cursos_estudiantes add constraint fk_estudiantes foreign key (id_estudiante) references usuarios;